create DATABASE IF NOT EXISTS zibomines CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP TABLE IF EXISTS VISITOR_COUNTER;
CREATE TABLE VISITOR_COUNTER(
    counter_id int AUTO_INCREMENT PRIMARY KEY ,
    ip varchar(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;